### ISSUE TITLE
Cache location is required when cache type is "S3"

### ISSUE THREAD

**Issue by KaKeimei** [cloudposse/terraform-aws-codebuild#100]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Cannot create code build with following settings:   
  cache_type = "S3"
  cache_bucket_suffix_enabled = true

## Steps to Reproduce
This happens for the first time planing while suffix is not available
1. cache_type S3 and cache_bucket_suffix_enabled 
2. terraform plan

cache_bucket_suffix_enabled  = false fix this

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: OSX
 - Version [e.g. 10.15]

## Additional Context
```
╷
│ Error: cache location is required when cache type is "S3"
│ 
│   with module.codebuild.aws_codebuild_project.default[0],
│   on modules/codebuild/main.tf line 292, in resource "aws_codebuild_project" "default":
│  292: resource "aws_codebuild_project" "default" {
│ 

```

**Comment by nitrocode** [comment]
@KaKeimei is this still an issue with the latest version ?

Please confirm and we can reopen.
