### ISSUE TITLE
Allow Type (& Source) to be set by variables 

### ISSUE THREAD

**Issue by atkinchris** [cloudposse/terraform-aws-codebuild#21]
The `type` for `aws_codebuild_project` is hardcoded to `CODEPIPELINE` - allowing this to be set by variables, would allow the module to be used for GitHub sources.

https://github.com/cloudposse/terraform-aws-codebuild/blob/4767ce77c1b324f71d0cc2bc585a49e90c4d2562/main.tf#L208

Happy to raise a PR if this would fit with your vision for the module.

**Comment by osterman** [comment]
@atkinchris thank for reaching out! Sounds like a reasonable request. We'll happily review your PR, if you can open one up. Also, join our slack team! https://slack.cloudposse.com if you're interested in connecting with the rest of our community. =)

**Comment by atkinchris** [comment]
Thanks @osterman - I've raised a PR here: https://github.com/cloudposse/terraform-aws-codebuild/pull/22

**Comment by osterman** [comment]
Thanks @atkinchris! We're grateful for your contributions.
