### ISSUE TITLE
source_type = CODECOMMIT  generates error 

### ISSUE THREAD

**Issue by hniemann** [cloudposse/terraform-aws-codebuild#23]
If you set source_type = CODECOMMIT

You will get the following error.

* aws_codebuild_project.default: [ERROR] Error creating CodeBuild project: InvalidInputException: Invalid input: when using CodePipeline both sourceType, and artifactType must be set to: CODEPIPELINE

**Comment by JamesFrost** [comment]
Setting `source_type` to anything other than `CODEPIPELINE` causes this error.
