### ISSUE TITLE
Missing build_timeout var

### ISSUE THREAD

**Issue by LeeGardiner** [cloudposse/terraform-aws-codebuild#29]
add variable build_timeout with a default of 60

**Comment by Stretch96** [comment]
Opened a PR for this: https://github.com/cloudposse/terraform-aws-codebuild/pull/30

**Comment by osterman** [comment]
@Stretch96 thanks for this! I was literally about to go implement it when I saw you had just submitted the PR.

**Comment by osterman** [comment]
Also adding badge support: https://github.com/cloudposse/terraform-aws-codebuild/pull/31
