### ISSUE TITLE
Add Input varaible to allow specifing the code build cached bucket name

### ISSUE THREAD

**Issue by solittlework** [cloudposse/terraform-aws-codebuild#34]
It would be nice of introducing a new variable, such as 'cached_s3_bucket' to specify the cached s3 bucket name for code build. This variable variable would be in active when the 'cache_enabled' variable is set to 'true'.

**Comment by Stretch96** [comment]
Is the aim here to be able to provide the name of an S3 bucket that already exists, or is it to be able to choose the name of the S3 bucket that is created?

**Comment by solittlework** [comment]
For us, we want to choose the S3 bucket which is already created. Otherwise, our project will have lots of s3 buckets.

**Comment by aknysh** [comment]
@solittlework  thanks for the suggestion!
Can you open a PR for that? We'll review promptly

**Comment by jamengual** [comment]
no updates for a long time, closing
