### ISSUE TITLE
Support for Terraform 0.12

### ISSUE THREAD

**Issue by zbikmarc** [cloudposse/terraform-aws-codebuild#45]
## What is this about

Looks like `terraform-aws-codebuild:0.16.0` does not support Terraform 0.12

## Expected behaviour

Run `terraform-aws-codebuild` with Terraform 0.12

## Detailed errors:
```
Error: Missing resource instance key

  on .terraform/modules/build/main.tf line 144, in data "aws_iam_policy_document" "permissions_cache_bucket":
 144:       "${aws_s3_bucket.cache_bucket.arn}",

Because aws_s3_bucket.cache_bucket has "count" set, its attributes must be
accessed on specific instances.

For example, to correlate with indices of a referring resource, use:
    aws_s3_bucket.cache_bucket[count.index]

```
Or similar for lines:
- `101`
- `144`
- `145`
- `152`
- `153`
- `159`
- `165`

Those are relatively easy to fix, however when those are fixed, other ones pop up.

```
Error: Unsupported argument

  on .terraform/modules/build/main.tf line 174, in resource "aws_codebuild_project" "default":
 174:   cache = ["${local.cache}"]

An argument named "cache" is not expected here. Did you mean to define a block
of type "cache"?


Error: Unsupported argument

  on .terraform/modules/build/main.tf line 182, in resource "aws_codebuild_project" "default":
 182:     environment_variable = [{

An argument named "environment_variable" is not expected here. Did you mean to
define a block of type "environment_variable"?
```

**Comment by Jamie-BitFlight** [comment]
This module hasn't been upgraded, but i expect @osterman has it on his list along with the other 120 modules.

If I can get to it I will, otherwise if you have time to fork the repo, and make a pull request of the upgrade its likely to be merged very quickly.

**Comment by zbikmarc** [comment]
Meantime I started to port it by myself, maybe I will be able to do this. If so I will create PR.
