### ISSUE TITLE
Option to enable local cache

### ISSUE THREAD

**Issue by drselump14** [cloudposse/terraform-aws-codebuild#49]
Hello, is there any way to set the cache location as "LOCAL" ?
I need it for speeding up docker build.

I'm happy to open PR if necessary.

**Comment by donutloop** [comment]
I also need to configure cache options

**Comment by drselump14** [comment]
I opened a pull request #50 for this feature

**Comment by ivanmartos** [comment]
I guess that with https://github.com/cloudposse/terraform-aws-codebuild/releases/tag/0.18.0 this is resolved, right?

**Comment by drselump14** [comment]
Yes, you're right.. thanks for reminding me.. I'll close this issue
