### ISSUE TITLE
Environment variables from SSM

### ISSUE THREAD

**Issue by ivanmartos** [cloudposse/terraform-aws-codebuild#51]
Would it be possible to specify env variables to be retrieved from SSM? This is supported by https://www.terraform.io/docs/providers/aws/r/codebuild_project.html

**Comment by barnou** [comment]
Hello,

Thank you for this module, it's great!
But what would make it even better would be to be able to add a type to the variables, as described in the terraform documentation! (`PARAMETER_STORE`, `PLAINTEXT`, and `SECRETS_MANAGER`)

Thank you very much!

**Comment by jamengual** [comment]
@barnou you can open a PR for it and we can review it.
