### ISSUE TITLE
Support of Other AWS CodeBuild Containers

### ISSUE THREAD

**Issue by bnippercg** [cloudposse/terraform-aws-codebuild#56]
## Describe the Feature

AWS Code Build supports multiple "Environment Types" as listed on the [AWS API Documentation under Project Environment](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectEnvironment.html)

From this we can find that the valid values are:
`WINDOWS_CONTAINER | LINUX_CONTAINER | LINUX_GPU_CONTAINER | ARM_CONTAINER`

Additionally the [Terraform aws_codebuild_project](https://www.terraform.io/docs/providers/aws/r/codebuild_project.html) exposes the ability for this value to be set as well, albeit in the example they have it set to one of the valid types.

I would propose that this element be exposed in the cloudposse terraform-aws-codebuild as:
`build_environment_type`

## Expected Behavior

When this new element is set it will impact the AWS CodeBuild Environment type.

## Use Case

Will enable the ability to have AWS CodeBuild to run as:
- WINDOWS
- LINUX
- LINUX_GPU
- ARM

## Describe Ideal Solution

The module supports setting `build_environment_type` or exposes this via some other similar element name.

## Alternatives Considered

The ability to run builds that require windows specific features (i.e. PowerShell) are not supported using the CloudPosse version of Terraform AWS CodeBuild module.

**Comment by bnippercg** [comment]
Happy to submit a PR to attempt to add this, sorry if missed where to request to make a PR or failing to follow any other process.

Big fan of the work CloudPosse is doing.

**Comment by brcnblc** [comment]
Hi bnippercg,

I've added `build_environment_type`support. It also adds many other lacking features such as private repository authorization, git clone depth secret manager access.
You may find it at my fork which is waiting to be reviewed.
https://github.com/brcnblc/terraform-aws-codebuild
