### ISSUE TITLE
Support AWS Provider 3

### ISSUE THREAD

**Issue by dennis-grunert** [cloudposse/terraform-aws-codebuild#65]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
The version of the AWS Provider is pinned to 2.x in `versions.tf`. Since an installed version of AWS provider [must satisfy](https://www.terraform.io/docs/configuration/terraform.html#specifying-a-required-terraform-version) the`required_providers` blocks of all child modules, the missing support of AWS Provider 3.x of this module blocks an upgrade for each project using it.

## Expected Behavior
This module can be used with AWS Provider 3.x.

## Additional Context
AWS Provider 3.0 was released on 2020-07-31. No newer versions of AWS Provider 2.x will be released. Therefore, all users of this plugin need an upgrade urgently.

**Comment by jayzalowitz** [comment]
This is a hugely painful issue for me right now
