### ISSUE TITLE
mfa_enable default setting preventing apply of updated module

### ISSUE THREAD

**Issue by jhosteny** [cloudposse/terraform-aws-codebuild#76]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
The module was updated to include a versioning configuration, with the default set to enable it, with `mfa_delete` also defaulted to true. I cannot seem to find a sequence of operations that allows me to apply this module cleanly. After updating the module, I encountered the initial problem:

```
Error: Error putting S3 versioning: AccessDenied: Mfa Authentication must be used for this request
	status code: 403, request id: AB2CBFAECF246E3B, host id: Y3bl2wZs+SeA84/5sb1cl3jahXB/a0Cv+ejQJkfeSeHX4SLce1Dyl4TpS3fSkI3eGpJC64OmBtk=
```

I then created a set of admin IAM keys for the root use in the production account, and attempted to update the MFA setting on the bucket:

```
aws s3api put-bucket-versioning --bucket <mybucket> --versioning-configuration Status=Enabled,MFADelete=Enabled --mfa "arn:aws:iam::<my-prod-acct>:mfa/root-account-mfa-device <token>"

An error occurred (InvalidBucketState) when calling the PutBucketVersioning operation: Mfa Authentication is not supported on a bucket with lifecycle configuration. Delete lifecycle configuration before enabling Mfa Authentication.
```

I manually removed the lifecycle rule, and was then able to update the setting. After that, I attempted to re-apply, but got the following error:

```
Error: Error putting S3 lifecycle: InvalidBucketState: Cannot put lifecycle configuration on a bucket that has MFA enabled
	status code: 409, request id: FYBY7PBQ9Y2Z3J6T, host id: bSWBYWc81xImMC0PTUT7xNXlGCkBw8ZwvQ01xUJKhERs9EK/QWHNhuMob02ROtd6nUwMfmhDI4E=
```

Finally, I tried to simply delete the build bucket, and let terraform re-create, but go the following:

```
Error: Error putting S3 versioning: AccessDenied: Mfa Authentication must be used for this request
	status code: 403, request id: A8ACED58533FAAD7, host id: qtnzSmWWV8g/TFbhkbfmwm84SwuTuzXEE0QK2pqfNe3mDaHPPyWjNS0ddQPe4Q4yhXwYY4QCDGk=
```

So, it seems the issue is that you cannot add this setting unless you are the root user on the account, which seems at odds with running in an assumed role.

Note that the accounts were created via the reference architecture, and I am applying the module in geodesic under the assume role for access to the prod account, from the MFA-enable IAM admin user in the root account.

## Expected Behavior
Module will successfully apply

## Steps to Reproduce
Update module on existing codebuild project, and re-apply.

## Screenshots
N/A

## Environment (please complete the following information):
Ubuntu 20.04
Terraform 0.13.6

## Additional Context
This issue was encountered while using the module as part of the https://github.com/cloudposse/terraform-aws-ecs-web-app module.

**Comment by jhosteny** [comment]
Hi @maximmi do you have a suggestion here? I can also add a PR that changes the setting to `false`, but I didn't want to do so until I had some feedback on perhaps how to work around this.

**Comment by jamengual** [comment]
@jhosteny do you use AWS organizations? maybe there is SCPs in place?

**Comment by jhosteny** [comment]
I do use AWS orgs, but SCPs are disabled. For reference, the accounts were built out with the reference arch. So, I am assuming a role in my `prod` account with my MFA-enabled IAM user from the root account (e.g., the normal `assume-role` in geodesic).

**Comment by zpg-khanh** [comment]
@jhosteny Did you find a resolution to this issue?

**Comment by doug-skinner** [comment]
@jhosteny looks like you closed this a few months after opening it. Would you mind sharing how you were able to get around this?
